# Change these first
owner: ikudanet # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ikuda.net
    url: https://ikuda.net
    icon: https://a.ikuda.net/favicon.png
  - name: Cloudflare R2 @ a.ikuda.net
    url: https://a.ikuda.net
    icon: https://a.ikuda.net/misc/images/upptime/cloudflare-icon.png
    expectedStatusCodes:
      - 404
  - name: ikuda.net archive
    url: https://archive.ikuda.net
    icon: https://a.ikuda.net/favicon.png
    expectedStatusCodes:
      - 404
  - name: Upptime
    url: https://upptime.ikuda.net
    icon: https://a.ikuda.net/misc/images/upptime/icon.svg

assignees:
  - aceikuda

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.ikuda.net
  # baseUrl: /your-repo-name
  logoUrl: https://a.ikuda.net/misc/images/upptime/icon.svg
  name: ikuda.net Upptime
  introTitle: "**Upptime** is an open-source uptime monitor & status page, powered by GitHub Actions."
  introMessage: 
  navbar:
    - title: status
      href: /
    - title: ikuda.net
      href: https://ikuda.net/
    - title: github
      href: https://github.com/$OWNER/$REPO
  metaTags:
    - name: "robots"
      content: "noindex, nofollow"

skipDescriptionUpdate: true
skipTopicsUpdate: true

# https://upptime.js.org/docs/configuration